data:extend({
    -- { Difficulty } --
  {
    type = "string-setting",
    name = "more-enemies-gleba-difficulty",
    setting_type = "startup",
    order = "aab",
    default_value = "Vanilla",
    allowed_values = {"Easy", "Vanilla", "Vanilla+", "Hard", "Insanity"}
  },
    -- { Small } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-count-of-owned-units",
      setting_type = "startup",
      order = "caa",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-count-of-owned-defensive-units",
      setting_type = "startup",
      order = "cab",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-friends-around-to-spawn",
      setting_type = "startup",
      order = "cac",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-defensive-friends-around-to-spawn",
      setting_type = "startup",
      order = "cad",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-gleba-small",
      setting_type = "startup",
      order = "cae",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-gleba-small",
      setting_type = "startup",
      order = "caf",
      default_value = 150,
      minimum_value = 1,
  },
  -- { Regular } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-units",
      setting_type = "startup",
      order = "cba",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-defensive-units",
      setting_type = "startup",
      order = "cbb",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-friends-around-to-spawn",
      setting_type = "startup",
      order = "cbc",
      default_value = 3,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-defensive-friends-around-to-spawn",
      setting_type = "startup",
      order = "cbd",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-gleba",
      setting_type = "startup",
      order = "cbe",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-gleba",
      setting_type = "startup",
      order = "cbf",
      default_value = 150,
      minimum_value = 1,
  }
})