data:extend({
    -- { Biters } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-biter",
      setting_type = "startup",
      order = "aaa",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-defensive-units-biter",
      setting_type = "startup",
      order = "aab",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-biter",
      setting_type = "startup",
      order = "aac",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-defensive-friends-around-to-spawn-biter",
      setting_type = "startup",
      order = "aad",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-biter",
      setting_type = "startup",
      order = "aae",
      default_value = 360,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-biter",
      setting_type = "startup",
      order = "aaf",
      default_value = 150,
      minimum_value = 0,
  },
  -- { Spitters } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-spitter",
      setting_type = "startup",
      order = "aba",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-defensive-units-spitter",
      setting_type = "startup",
      order = "abb",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-spitter",
      setting_type = "startup",
      order = "abc",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-defensive-friends-around-to-spawn-spitter",
      setting_type = "startup",
      order = "abd",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-spitter",
      setting_type = "startup",
      order = "abe",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-spitter",
      setting_type = "startup",
      order = "abf",
      default_value = 150,
      minimum_value = 1,
  }
})