data:extend({
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-biter",
      setting_type = "startup",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-biter",
      setting_type = "startup",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-spitter",
      setting_type = "startup",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-spitter",
      setting_type = "startup",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-count-of-owned-units",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-friends-around-to-spawn",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-units",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-defensive-units",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-friends-around-to-spawn",
      setting_type = "startup",
      default_value = 3,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-defensive-friends-around-to-spawn",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 0,
  }
})