data:extend({
    -- { Difficulty } --
  {
    type = "string-setting",
    name = "more-enemies-nauvis-difficulty",
    setting_type = "startup",
    order = "aaa",
    default_value = "Vanilla",
    allowed_values = {"Easy", "Vanilla", "Vanilla+", "Hard", "Insanity"}
  },
    -- { Biters } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-biter",
      setting_type = "startup",
      order = "baa",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-defensive-units-biter",
      setting_type = "startup",
      order = "bab",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-biter",
      setting_type = "startup",
      order = "bac",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-defensive-friends-around-to-spawn-biter",
      setting_type = "startup",
      order = "bad",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-biter",
      setting_type = "startup",
      order = "bae",
      default_value = 360,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-biter",
      setting_type = "startup",
      order = "baf",
      default_value = 150,
      minimum_value = 0,
  },
  -- { Spitters } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-units-spitter",
      setting_type = "startup",
      order = "bba",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-count-of-owned-defensive-units-spitter",
      setting_type = "startup",
      order = "bbb",
      default_value = 7,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-friends-around-to-spawn-spitter",
      setting_type = "startup",
      order = "bbc",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-nauvis-max-defensive-friends-around-to-spawn-spitter",
      setting_type = "startup",
      order = "bbd",
      default_value = 5,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-spitter",
      setting_type = "startup",
      order = "bbe",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-spitter",
      setting_type = "startup",
      order = "bbf",
      default_value = 150,
      minimum_value = 1,
  }
})