data:extend({
    -- { Small } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-count-of-owned-units",
      setting_type = "startup",
      order = "baa",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-count-of-owned-defensive-units",
      setting_type = "startup",
      order = "bab",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-friends-around-to-spawn",
      setting_type = "startup",
      order = "bac",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-small-max-defensive-friends-around-to-spawn",
      setting_type = "startup",
      order = "bad",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-gleba-small",
      setting_type = "startup",
      order = "bae",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-gleba-small",
      setting_type = "startup",
      order = "baf",
      default_value = 150,
      minimum_value = 1,
  },
  -- { Regular } --
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-units",
      setting_type = "startup",
      order = "bba",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-count-of-owned-defensive-units",
      setting_type = "startup",
      order = "bbb",
      default_value = 1,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-friends-around-to-spawn",
      setting_type = "startup",
      order = "bbc",
      default_value = 3,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-spawner-gleba-max-defensive-friends-around-to-spawn",
      setting_type = "startup",
      order = "bbd",
      default_value = 2,
      minimum_value = 0,
  },
  {
      type = "int-setting",
      name = "more-enemies-max-spawning-cooldown-gleba",
      setting_type = "startup",
      order = "bbe",
      default_value = 360,
      minimum_value = 1,
  },
  {
      type = "int-setting",
      name = "more-enemies-min-spawning-cooldown-gleba",
      setting_type = "startup",
      order = "bbf",
      default_value = 150,
      minimum_value = 1,
  }
})