local Armoured_Biters_Settings_Constants = require("libs.constants.settings.mods.armoured-biters.armoured-biters-settings-constants")

data:extend({
  -- { Armoured Biters } --
  Armoured_Biters_Settings_Constants.settings.NAUVIS_BITER_ARMOURED_MAX_COUNT_OF_OWNED_UNITS,
  Armoured_Biters_Settings_Constants.settings.NAUVIS_BITER_ARMOURED_MAX_COUNT_OF_OWNED_DEFENSIVE_UNITS,
  Armoured_Biters_Settings_Constants.settings.NAUVIS_BITER_ARMOURED_MAX_FRIENDS_AROUND_TO_SPAWN,
  Armoured_Biters_Settings_Constants.settings.NAUVIS_BITER_ARMOURED_MAX_DEFENSIVE_FRIENDS_AROUND_TO_SPAWN,
  Armoured_Biters_Settings_Constants.settings.NAUVIS_ARMOURED_BITER_MAX_SPAWNING_COOLDOWN,
  Armoured_Biters_Settings_Constants.settings.NAUVIS_ARMOURED_BITER_MIN_SPAWNING_COOLDOWN
})